{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"name":"Copia di Copia di VN_13. Error-handling-and-testing_v2.ipynb","provenance":[{"file_id":"1mdFMeCfR8dPFcHAUqIwrseqbOC25HtNm","timestamp":1647356005997},{"file_id":"https://github.com/futureCodersSE/python-programming-for-data/blob/main/Worksheets/13_Error_handling_and_testing.ipynb","timestamp":1646736231083}],"collapsed_sections":[]},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"}},"cells":[{"cell_type":"markdown","metadata":{"id":"llhPjzuu7KLX"},"source":["# Dealing with errors\n","---\n","\n","There are various types of error that a well written function will handle but which can sometimes be forgotten.\n","\n","Errors can be categorised into:\n","*  Syntax errors  \n","errors in the code that stop it from being interpreted and run - these are often picked up by the code editor, or by Python when it tries to translate the code before running it  \n","\n","*  Logic errors  \n","these are hard to pick up and rely on good testing or user feedback.  A logic error will result in 'wrong' data or functionality  \n","\n","*  Runtime errors  \n","these are generally caused by operations that work perfectly well with the 'right' data but fall over if they encounter the 'wrong' data.\n","\n","### Exercise 1  \n","---\n","\n","The code below has a syntax error. Correct the error and run the code.\n"]},{"cell_type":"code","source":[""],"metadata":{"id":"kk2MRLg6ZEBX","executionInfo":{"status":"ok","timestamp":1650191830438,"user_tz":-120,"elapsed":20,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}}},"execution_count":null,"outputs":[]},{"cell_type":"code","metadata":{"id":"fqvRJOFz7HEs","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650191830439,"user_tz":-120,"elapsed":18,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"adf1d738-9ade-4316-888b-a8831161e3ea"},"source":["def get_list():\n","  mylist = [\"red\",'yellow','pink',\"green\",'orange',\"purple\",\"blue\"]\n","  return mylist\n","\n","print(get_list())"],"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["['red', 'yellow', 'pink', 'green', 'orange', 'purple', 'blue']\n"]}]},{"cell_type":"markdown","metadata":{"id":"G8fVmU5h86Dn"},"source":["### Exercise 2 \n","---\n","\n","The code below has a `logic` error.  The function is being run by a test, which will fail on first run.  Correct the error and run the code to get the test to pass."]},{"cell_type":"code","metadata":{"id":"irDAREWJ9AdV","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650191830439,"user_tz":-120,"elapsed":13,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"07d90546-85f5-43e3-c0fa-3163368fcafb"},"source":["def calculate_average(nums):\n","  total = 0\n","  for num in nums:\n","    total += num\n","  ave=total/len(nums)\n","  return ave\n","\n","# Test\n","actual = calculate_average([4,2,6,8,3,1])\n","expected = 4\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)\n"],"execution_count":2,"outputs":[{"output_type":"stream","name":"stdout","text":["Test passed\n"]}]},{"cell_type":"markdown","metadata":{"id":"sBXNkQqJ9bX-"},"source":["### Exercise 3\n","---\n","\n","The code below does not have any errors and will run perfectly well, until it receives some data that doesn't fit what it is expecting.  Run the code, entering the number 16"]},{"cell_type":"code","metadata":{"id":"1A5DkNo59ZZA","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650192177254,"user_tz":-120,"elapsed":3438,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"8c11a29e-29eb-43cb-ebca-7a418e8cf33b"},"source":["def get_user_input():\n","  user_input = input(\"Please enter a number \")\n","  return int(user_input)#Need to return an integer because input() always returns a string \n","\n","### Test 1 - user enters 16 ###\n","print(\"Test 1 - with valid integer\")\n","actual = get_user_input() / 2\n","expected = 8\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)\n"],"execution_count":6,"outputs":[{"output_type":"stream","name":"stdout","text":["Test 1 - with valid integer\n","Please enter a number 16\n","Test passed\n"]}]},{"cell_type":"markdown","metadata":{"id":"1UI44hURAgf2"},"source":["### Exercise 4\n","---\n","\n","The solution you have just implemented will solve the known problem that input() always returns a string, BUT, what if the user actually enters something that isn't a number?  Run the code below, it will crash with the input **six** but we don't want users to be informed of an input error by the program crashing! \n","\n","\n","The runtime error occurs when it is trying to divide numbers that are not valid\n","  \n","\n","```\n","Test 1 - with valid integer\n","Please enter a number 16\n","Test passed\n","\n","Test 2 - with invalid integer\n","Please enter a number six\n","Invalid number, run the function again\n","Test passed\n","```"]},{"cell_type":"code","metadata":{"id":"2ce-rQZ6gmBM","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650192851991,"user_tz":-120,"elapsed":20042,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"743cefaf-2004-47a6-bf40-0a66a2327be6"},"source":["def get_user_input():\n","  try:\n","    user_input = int(input(\"Please enter a number \"))\n","    return user_input\n","  except:   \n","    print(\"Invalid number, run the function again\")\n","    return 0\n","\n","## Test 1 - user enters 16 ###\n","#print(\"Test 1 - with valid integer\")\n","actual = get_user_input() / 2\n","expected = 8\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)\n","\n","### Test 2 - user enters six ###\n","print(\"\\nTest 2 - with invalid integer\")\n","# ADD YOUR TEST CODE HERE #\n","actual = get_user_input() \n","expected = 0\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)\n","\n","### Test 3 - user enters 0 ###\n","print(\"\\nTest 3 - with 0\")\n","# ADD YOUR TEST CODE HERE #\n","actual = get_user_input() \n","expected = 0\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)"],"execution_count":8,"outputs":[{"output_type":"stream","name":"stdout","text":["Please enter a number 16\n","Test passed\n","\n","Test 2 - with invalid integer\n","Please enter a number six\n","Invalid number, run the function again\n","Test passed\n","\n","Test 3 - with 0\n","Please enter a number 0\n","Test passed\n"]}]},{"cell_type":"markdown","metadata":{"id":"QmeO2NR0gpYi"},"source":["### Exercise 5 - add a third test\n","---\n","\n","Add a Test 3, to test for the user just pressing enter and not entering anything at all) The expected result will be the same as Test 2\n","\n"]},{"cell_type":"code","metadata":{"id":"z69J6BTDBCMG","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650192935341,"user_tz":-120,"elapsed":10349,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"abd9eb9a-d5ee-46df-cfeb-f8f5cba8ae93"},"source":["def get_user_input():\n","  try:\n","    user_input = int(input(\"Please enter a number \"))\n","    return user_input\n","  except:\n","    print(\"Invalid number, run the function again\")\n","    return 0\n","\n","### Test 1 - user enters 16 ###\n","print(\"Test 1 - with valid integer\")\n","actual = get_user_input() / 2\n","expected = 8\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)\n","\n","### Test 2 - user enters six ###\n","print(\"\\nTest 2 - with invalid integer\")\n","# ADD YOUR TEST CODE HERE #\n","actual = get_user_input() \n","expected = 0\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)\n","\n","### Test 3 - user enters nothing ###\n","print(\"\\nTest 3 - with empty integer\")\n","# ADD YOUR TEST CODE HERE #\n","actual = get_user_input() \n","expected = 0\n","if  actual == expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, expected\", expected, \"but got\", actual)\n","\n"],"execution_count":10,"outputs":[{"output_type":"stream","name":"stdout","text":["Test 1 - with valid integer\n","Please enter a number 16\n","Test passed\n","\n","Test 2 - with invalid integer\n","Please enter a number six\n","Invalid number, run the function again\n","Test passed\n","\n","Test 3 - with empty integer\n","Please enter a number \n","Invalid number, run the function again\n","Test passed\n"]}]},{"cell_type":"markdown","metadata":{"id":"Ol_Z4kRpJEVr"},"source":["### Exercise 6 - opening a file\n","---\n","\n","Write a function that will return an open file if it is given the file name.  If the file doesn't exist, a message should be shown to the user and the function should return None.  If the file does exist, and is opened correctly, the function should return the file to the caller.  \n","\n","The code has been started for you and two tests have been written.  \n","\n","Run the program with the second test commented out, to test that it works if the file doesn't exist (this assumes that you don't have a file called `error.txt` in the same directory as this notebook.  \n","\n","Now create a text file called **valid_file.txt** in the same directory as this notebook.  Uncomment the second test and run again.  Both tests should now pass.\n","\n","*Note*:  The tests look a little different now - this time instead of comparing actual with expected, the test looks at if the actual result is None or not None.  This is because it is impossible to tell what result will be returned for a valid file, as this is dependent on the file and the operating system.  It is sufficient to know that the file is opened if it exists and that the program doesn't crash if it doesn't.\n","\n"]},{"cell_type":"code","metadata":{"id":"F2syhzV7KzB7","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650193568453,"user_tz":-120,"elapsed":28721,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"02363dd4-2319-4fbe-f1a0-24c1094a66a5"},"source":["import os\n","#there are 2 options to solve this exercise\n","\n","# #option 1: upload and read the file\n","# #from google.colab import files\n","# def get_file(filename):\n","#   try:\n","# #this will upload the file on the drive \n","#     file = files.upload()\n","#     rdfile = open(upload[filename])\n","#     return rdfile\n","#   except:\n","#     print(\"File does not exist\")\n","#     return None\n","\n","# # Test 1 - try to open a file that doesn't exist\n","# print(\"Test 1 file doesn't exist\")\n","# actual = get_file(\"error.txt\")\n","# if actual is None:\n","#   print(\"Test passed\")\n","# else:\n","#   print(\"Test failed, should have received None\")\n","\n","# # Test 2 - try to open a file that does exist\n","# print(\"\\nTest 2 file does exist\")\n","# file=\"valid_file.txt\"\n","# actual = get_file(file)\n","\n","\n","\n","#option 2\n","from google.colab import drive\n","drive.mount('/content/gdrive/') #mount the gdrive\n","\n","def get_file(filename):\n","  try:\n","    file = open(filename)\n","    return file\n","  except:\n","    return None\n","\n","# Test 1 - try to open a file that doesn't exist\n","print(\"Test 1: file doesn't exist\")\n","actual = get_file(\"error.txt\")\n","if actual is None:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, should have received None\")\n","\n","# Test 2 - try to open a file that does exist\n","print(\"\\nTest 2: file does exist\")\n","file=\"test.txt\"\n","dir = os.path.join(\"/content/gdrive/My Drive/Colab Notebooks/\", file)\n","actual = get_file(dir)\n","\n","if actual is not None:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed, should have received file\")"],"execution_count":11,"outputs":[{"output_type":"stream","name":"stdout","text":["Mounted at /content/gdrive/\n","Test 1: file doesn't exist\n","Test passed\n","\n","Test 2: file does exist\n","Test failed, should have received file\n"]}]},{"cell_type":"markdown","metadata":{"id":"OACfOBCiRJkZ"},"source":["### Exercise 7 - write a test\n","---\n","\n","The function in the code cell below will take two parameters (two integers), and will return the result of dividing the first by the second, rounded to 2 decimal places.  If either isn't a number, it will return -999999  (not an impossible answer but improbable).\n","\n","Write a test for this function that will run it with the numbers 15 and 3 and will expect the answer to be 5."]},{"cell_type":"code","metadata":{"id":"HScLyIF4SY6o","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650193724117,"user_tz":-120,"elapsed":402,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"4173c35b-bf27-4af5-9b9d-a71984cdef49"},"source":["def divide_nums(num1, num2):\n","  try:\n","    answer = num1 / num2\n","    return answer\n","  except:\n","    return -999999\n","\n","# Test 1 - works with valid numbers (15 divided by 3 is 5)\n","print(\"Test 1 - works with valid numbers (15 divided by 3 is 5)\")\n","ans=divide_nums(15, 3)\n","expected=5.0\n","if ans==expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")\n"],"execution_count":13,"outputs":[{"output_type":"stream","name":"stdout","text":["Test 1 - works with valid numbers (15 divided by 3 is 5)\n","Test passed\n"]}]},{"cell_type":"markdown","metadata":{"id":"eYfYXH9PTA5W"},"source":["### Exercise 8 - add two more tests\n","---\n","\n","Add two more tests for this function:\n","\n","*Test 2* - Test running the function with the numbers `(20, 0.3)` and expect the answer to be `66.67`\n","\n","*Test 3* - Test running the function with `(20, None)` and expect the answer to be `-999999`\n","\n","Run the tests and then **modify the function** so that the test using the numbers `(20, 0.3)` passes."]},{"cell_type":"code","metadata":{"id":"zYD_a_dlWIbf","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1650194095537,"user_tz":-120,"elapsed":452,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"bc8f61f9-439f-4af9-9591-effbf2ebe910"},"source":["def divide_nums(num1, num2):\n","  try:\n","    ratio = num1 / num2\n","    return round(ratio,2)\n","  except:\n","    return -999999\n"," \n","# Test 1 - works with valid numbers (15 divided by 3 is 5)\n","print(\"Test 1 - works with valid numbers (15 divided by 3 is 5)\")\n","ans=divide_nums(15, 3)\n","expected=5.0\n","if ans==expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")\n","\n","# Test 2 - works with valid numbers (20, 0.3)\n","print(\"\\nTest 2 - works with valid numbers (20, 0.3)\")\n","ans=divide_nums(20, 0.3)\n","expected=66.67\n","if ans==expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")\n","  print (ans)\n","\n","# Test 3 - works with valid numbers (invalid numbers)\n","print(\"\\nTest 3 - works with invalid numbers \")\n","ans=divide_nums(20,None)\n","expected=-999999\n","if ans==expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")"],"execution_count":14,"outputs":[{"output_type":"stream","name":"stdout","text":["Test 1 - works with valid numbers (15 divided by 3 is 5)\n","Test passed\n","\n","Test 2 - works with valid numbers (20, 0.3)\n","Test passed\n","\n","Test 3 - works with invalid numbers \n","Test passed\n"]}]},{"cell_type":"markdown","metadata":{"id":"ZaluV9ejWUqs"},"source":["### Exercise 9 - function with `try..except` and test\n","---\n","\n","Write a function to calculate the average of a list of numbers.\n","\n","Write a set of tests for this function to test that:  \n","*  a valid set of numbers, with a valid name works\n","*  it catches the error if the parameters are round the wrong way `(listname, numlist)` rather than `(numlist, listname)`\n","*  it catches the error is the list is empty (which might result in dividing by 0)\n","*  it catches the error if the numlist contains null values (None)\n","*  it shows the result `The average of the numbers in unnamed list is 4.5.` if the listname is an empty string.  Note:  this test may well fail unless you had code in your function to deal with the string being empty.  This is a logic error - change the code so that if the listname is \"\" it will be set to \"unnamed list\".  Then run the tests again, they should all pass."]},{"cell_type":"code","source":["def find_list_average(numlist, listname):\n","  try:\n","    sum=0.0\n","    if listname==\"\":\n","      listname=\"unnamed list\"\n","    for item in numlist:\n","      sum +=item\n","    average=sum/len(numlist)\n","    return round(average,2),\"The average of the numbers in \"+listname+\" is \"+str(average)+\" .\"  #we return two arguments  \n","  except:\n","    return (\"There was a problem\")\n","\n","#Test 1\n","print(\"Test 1: a valid set of numbers, with a valid name\")\n","avg,message=find_list_average([2,4,5], \"note\")\n","expected=3.67\n","if avg==expected:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")\n","\n","#Test 2\n","print(\"\\nTest 2: inputs in reverse order\")\n","avg=find_list_average(\"note\",[2,4,5])\n","# Check if variable is string \n","if isinstance(avg, str):\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")\n","\n","#Test 3 it catches the error is the list is empty (which might result in dividing by 0)\n","print(\"\\nTest 3: empty list\")\n","avg=find_list_average([],\"note\")\n","if isinstance(avg, str):\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")\n","\n","#Test 4 it catches the error if the numlist contains null values (None)\n","print(\"\\nTest 4: None values in list\")\n","avg=find_list_average([1,2,4,5,None],\"note\")\n","if isinstance(avg, str):\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")\n","\n","#Test 5 it shows the result The average of the numbers in unnamed list is 4.5. \n","print(\"\\nTest 5: unnamed list\")\n","avg,message=find_list_average([2,2,2,2],\"\")\n","exp_message=\"The average of the numbers in unnamed list is 2.0 .\"\n","print(message)\n","\n","if message==exp_message:\n","  print(\"Test passed\")\n","else:\n","  print(\"Test failed\")"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"b1D4ysVRRHSd","executionInfo":{"status":"ok","timestamp":1650194798594,"user_tz":-120,"elapsed":409,"user":{"displayName":"Valentina Nacar","userId":"03922103004082663720"}},"outputId":"90838e94-4ced-4e8a-ef45-3fb9e28c90b5"},"execution_count":15,"outputs":[{"output_type":"stream","name":"stdout","text":["Test 1: a valid set of numbers, with a valid name\n","Test passed\n","\n","Test 2: inputs in reverse order\n","Test passed\n","\n","Test 3: empty list\n","Test passed\n","\n","Test 4: None values in list\n","Test passed\n","\n","Test 5: unnamed list\n","The average of the numbers in unnamed list is 2.0 .\n","Test passed\n"]}]},{"cell_type":"markdown","metadata":{"id":"yQyytEbnZ1lw"},"source":["# Reflection\n","----\n","\n","## What skills have you demonstrated in completing this notebook?"]},{"cell_type":"markdown","metadata":{"id":"M9IqO6KNbSUk"},"source":["Your answer: "]},{"cell_type":"markdown","metadata":{"id":"Zgexd27sZ1ly"},"source":["## What caused you the most difficulty?"]},{"cell_type":"markdown","metadata":{"id":"aDYmIIcEbT7x"},"source":["Your answer: "]}]}